language: php

php:
  - 5.6
  - 5.5

install:
 - mysql -e 'CREATE DATABASE react_mysql_test;'
 - travis_retry composer install --prefer-source --no-interaction

script:
 - php vendor/bin/phpunit --coverage-text
